cities = {
    "Africa": [
        "Addis Ababa",
        "Alexandria",
        "Cairo",
        "Johannesburg",
        "Lagos",
    ],
    "Asia": [
        "Beijing",
        "Delhi",
        "Hanoi",
        "Hong Kong",
        "Jakarta",
        "Manila",
        "Mumbai",
        "Osaka",
        "Seoul",
        "Shanghai",
        "Tokyo",
    ],
    "Middle East": [
        "Baghdad",
        "Dubai",
        "Gaza",
        "Istanbul",
        "Jerusalem",
        "Tehran",
        "Tel Aviv",
    ],
    "Europe": [
        "Athens",
        "Barcelona",
        "Berlin",
        "Helsinki",
        "London",
        "Madrid",
        "Moscow",
        "Paris",
    ],
    "North America": [
        "Anchorage",
        "Atlanta",
        "Billings",
        "Boise",
        "Boston",
        "Chicago",
        "Dallas",
        "Denver",
        "Detroit",
        "Honolulu",
        "Houston",
        "Huntsville",
        "Indianapolis",
        "Kansas City",
        "Las Vegas",
        "Los Angeles",
        "Mexico City",
        "Miami",
        "Nashville",
        "New Orleans",
        "New York City",
        "Omaha",
        "Philadelphia",
        "Phoenix",
        "Portland",
        "Salt Lake City",
        "Seattle",
        "Tijuana",
        "Toronto",
        "Washington",
    ],
    "Central America": [
        "Santo Domingo",
        "Havana",
        "Guatemala City",
        "Port-au-Prince",
        "San Juan",
        "Panama City",
        "Tegucigalpa",
        "San Jose",
        "Kingston",
        "San Salvador",
    ],
    "South America": [
        "Bogotá",
        "Brasilia",
        "Buenos Aires",
        "Lima",
        "Porto Alegre",
        "Recife",
        "Rio de Janeiro",
        "San Salvador",
        "Santiago",
        "São Paulo",
    ],
    "Oceania": [
        "Adelaide",
        "Auckland",
        "Brisbane",
        "Canberra",
        "Gold Coast",
        "Melbourne",
        "Newcastle",
        "Perth",
        "Pohnpei",
        "Sydney",
        "Wellington",
    ],
}

world_cities = [city for continent in cities.values() for city in continent]
