world_cities = [
    "Abidjan", "Addis Ababa", "Ahmedabad", "Alexandria", "Ankara", "Baghdad", "Bangalore", 
    "Bangkok", "Barcelona", "Beijing", "Belo Horizonte", "Bogota", "Buenos Aires", "Cairo", 
    "Casablanca", "Chengdu", "Chennai", "Chicago", "Chittagong", "Chongqing", "Dar es Salaam", 
    "Delhi", "Dhaka", "Dongguan", "Foshan", "Guadalajara", "Guangzhou", "Hangzhou", "Harbin", 
    "Ho Chi Minh City", "Hong Kong", "Hyderabad", "Istanbul", "Jakarta", "Jinan", "Johannesburg", 
    "Kabul", "Karachi", "Kinshasa", "Kolkata", "Kuala Lumpur", "Lagos", "Lahore", "Lima", 
    "London", "Los Angeles", "Luanda", "Madrid", "Manila", "Mexico City", "Moscow", "Mumbai", 
    "Nagoya", "Nairobi", "Nanjing", "New York", "Osaka", "Paris", "Pune", "Qingdao", "Rio de Janeiro", 
    "Riyadh", "Saint Petersburg", "Santiago", "Sao Paulo", "Seoul", "Shanghai", "Shenzhen", 
    "Singapore", "Surat", "Suzhou", "Sydney", "Taipei", "Tehran", "Tianjin", "Tokyo", "Toronto", 
    "Wuhan", "Xi'an", "Yangon", "Zhengzhou", "Accra", "Algiers", "Amman", "Antananarivo", 
    "Athens", "Auckland", "Baku", "Bamako", "Bandung", "Belo Horizonte", "Bhopal", "Brasilia", 
    "Brisbane", "Brussels", "Bucharest", "Budapest", "Cali", "Cape Town", "Caracas", "Changsha", 
    "Changzhou", "Chengdu", "Chittagong", "Colombo", "Curitiba", "Dakar", "Damascus", "Davao City", 
    "Douala", "Durban", "Faisalabad", "Fortaleza", "Fukuoka", "Fuzhou", "Giza", "Guayaquil", 
    "Hanoi", "Havana", "Hefei", "Hohhot", "Ibadan", "Incheon", "Izmir", "Jaipur", "Jeddah", 
    "Kano", "Khartoum", "Kigali", "Kuwait City", "Kyiv", "Lanzhou", "Lusaka", "Maputo", "Mashhad", 
    "Medan", "Medellin", "Minsk", "Monrovia", "Montevideo", "Multan", "Nagpur", "Nanchang", 
    "Nanning", "Nashik", "Naypyidaw", "Niamey", "Ouagadougou", "Palembang", "Patna", "Perth", 
    "Phnom Penh", "Port Harcourt", "Porto Alegre", "Pretoria", "Puebla", "Quito", "Recife", 
    "Riverside", "Salvador", "San Antonio", "San Diego", "San Francisco", "San Jose", "San Juan", 
    "Santa Cruz", "Sapporo", "Semarang", "Sendai", "Shantou", "Shenyang", "Shijiazhuang", 
    "Sofia", "Stockholm", "Surabaya", "Tabriz", "Taiyuan", "Tangshan", "Tashkent", "Thessaloniki", 
    "Tijuana", "Tirana", "Tunis", "Ulaanbaatar", "Urumqi", "Valencia", "Vancouver", "Vienna", 
    "Warsaw", "Winnipeg", "Yaounde", "Yekaterinburg", "Yerevan", "Zibo", "Zurich",
    "Albuquerque", "Arlington", "Atlanta", "Austin", "Baltimore", "Boston", "Charlotte", 
    "Chicago", "Cincinnati", "Cleveland", "Colorado Springs", "Columbus", "Dallas", "Denver", 
    "Detroit", "El Paso", "Fort Worth", "Fresno", "Houston", "Indianapolis", "Jacksonville", 
    "Kansas City", "Las Vegas", "Long Beach", "Louisville", "Memphis", "Mesa", "Miami", 
    "Milwaukee", "Minneapolis", "Nashville", "New Orleans", "New York", "Oakland", "Oklahoma City", 
    "Omaha", "Philadelphia", "Phoenix", "Pittsburgh", "Portland", "Raleigh", "Sacramento", 
    "San Antonio", "San Diego", "San Francisco", "San Jose", "Seattle", "Tucson", "Tulsa", 
    "Virginia Beach", "Washington", "Wichita", "Anchorage", "Bakersfield", "Chandler", 
    "Chesapeake", "Corpus Christi", "Durham", "Garland", "Glendale", "Greensboro", "Henderson", 
    "Hialeah", "Honolulu", "Irvine", "Irving", "Laredo", "Lubbock", "Madison", "Norfolk", 
    "Orlando", "Plano", "Reno", "Scottsdale", "Shreveport", "Spokane", "St. Louis", "St. Paul", 
    "St. Petersburg", "Stockton", "Tampa", "Toledo", "Winston-Salem"
]

world_cities.sort()
