cities = {
    "Africa": [
        "Addis Ababa",
        "Alexandria",
        "Cairo",
        "Johannesburg",
        "Lagos",
    ],
    "Asia": [
        "Beijing",
        "Delhi",
        "Hanoi",
        "Hong Kong",
        "Jakarta",
        "Manila",
        "Mumbai",
        "Osaka",
        "Seoul",
        "Shanghai",
        "Tokyo",
    ],
    "Middle East": [
        "Baghdad",
        "Dubai",
        "Gaza",
        "Istanbul",
        "Jerusalem",
        "Tehran",
        "Tel Aviv",
    ],
    "Europe": [
        "Athens",
        "Barcelona",
        "Berlin",
        "Helsinki",
        "London",
        "Madrid",
        "Moscow",
        "Paris",
    ],
    "North America": [
        "Albuquerque",
        "Anchorage",
        "Atlanta",
        "Austin",
        "Baltimore",
        "Bangor",
        "Baton Rouge",
        "Billings",
        "Birmingham",
        "Boise",
        "Boston",
        "Buffalo",
        "Calgary",
        "Charlotte",
        "Chicago",
        "Cincinnati",
        "Cleveland",
        "Columbus",
        "Dallas",
        "Denver",
        "Detroit",
        "Edmonton",
        "El Paso",
        "Fairbanks",
        "Fort Lauderdale",
        "Fort Myers",
        "Fort Worth",
        "Fresno",
        "Halifax",
        "Honolulu",
        "Houston",
        "Huntsville",
        "Indianapolis",
        "Jacksonville",
        "Kansas City",
        "Las Vegas",
        "Long Beach",
        "Louisville",
        "Los Angeles",
        "Madison",
        "Memphis",
        "Mexico City",
        "Miami",
        "Milwaukee",
        "Minneapolis",
        "Montgomery",
        "Montreal",
        "Nashua",
        "Nashville",
        "New Haven",
        "New Orleans",
        "New York City",
        "Newark",
        "Oakland",
        "Oklahoma City",
        "Omaha",
        "Orlando",
        "Ottawa",
        "Philadelphia",
        "Phoenix",
        "Pittsburgh",
        "Portland",
        "Providence",
        "Quebec City",
        "Raleigh",
        "Richmond",
        "Riverside",
        "Salt Lake City",
        "San Antonio",
        "San Diego",
        "San Francisco",
        "San Jose",
        "Saskatoon",
        "Seattle",
        "St. John's",
        "St. Louis",
        "St. Paul",
        "Tampa",
        "Tijuana",
        "Toronto",
        "Tucson",
        "Tulsa",
        "Virginia Beach",
        "Washington",
        "Wichita",
        "Winnipeg",
        "Vancouver",
        "Victoria",
    ],
    "Central America": [
        "Santo Domingo",
        "Havana",
        "Guatemala City",
        "Port-au-Prince",
        "San Juan",
        "Panama City",
        "Tegucigalpa",
        "San Jose",
        "Kingston",
        "San Salvador",
    ],
    "South America": [
        "Bogotá",
        "Brasilia",
        "Buenos Aires",
        "Lima",
        "Porto Alegre",
        "Recife",
        "Rio de Janeiro",
        "San Salvador",
        "Santiago",
        "São Paulo",
    ],
    "Oceania": [
        "Adelaide",
        "Auckland",
        "Brisbane",
        "Canberra",
        "Gold Coast",
        "Melbourne",
        "Newcastle",
        "Perth",
        "Pohnpei",
        "Sydney",
        "Wellington",
    ],
}

world_cities = [city for continent in cities.values() for city in continent]
