territories = {
    "Abidjan": "CI",
    "Accra": "GH",
    "Addis Ababa": "ET",
    "Algiers": "DZ",
    "Antananarivo": "MG",
    "Bamako": "ML",
    "Cairo": "EG",
    "Cape Town": "ZA",
    "Casablanca": "MA",
    "Dakar": "SN",
    "Dar es Salaam": "TZ",
    "Douala": "CM",
    "Durban": "ZA",
    "Ibadan": "NG",
    "Johannesburg": "ZA",
    "Kano": "NG",
    "Khartoum": "SD",
    "Kigali": "RW",
    "Kinshasa": "CD",
    "Lagos": "NG",
    "Luanda": "AO",
    "Lusaka": "ZM",
    "Maputo": "MZ",
    "Monrovia": "LR",
    "Nairobi": "KE",
    "Niamey": "NE",
    "Ouagadougou": "BF",
    "Port Harcourt": "NG",
    "Pretoria": "ZA",
    "Yaounde": "CM",
    "Ahmedabad": "IN",
    "Alexandria": "EG",
    "Almaty": "KZ",
    "Amman": "JO",
    "Ankara": "TR",
    "Baghdad": "IQ",
    "Baku": "AZ",
    "Bandung": "ID",
    "Bangalore": "IN",
    "Bangkok": "TH",
    "Beijing": "CN",
    "Bishkek": "KG",
    "Chengdu": "CN",
    "Chennai": "IN",
    "Chittagong": "BD",
    "Chongqing": "CN",
    "Colombo": "LK",
    "Damascus": "SY",
    "Davao City": "PH",
    "Delhi": "IN",
    "Dhaka": "BD",
    "Dongguan": "CN",
    "Fairbanks": "US",
    "Faisalabad": "PK",
    "Foshan": "CN",
    "Fukuoka": "JP",
    "Fuzhou": "CN",
    "Guangzhou": "CN",
    "Hangzhou": "CN",
    "Hanoi": "VN",
    "Harbin": "CN",
    "Hefei": "CN",
    "Ho Chi Minh City": "VN",
    "Hohhot": "CN",
    "Hong Kong": "HK",
    "Hyderabad": "IN",
    "Incheon": "KR",
    "Islamabad": "PK",
    "Istanbul": "TR",
    "Izmir": "TR",
    "Jaipur": "IN",
    "Jakarta": "ID",
    "Jeddah": "SA",
    "Jinan": "CN",
    "Kabul": "AF",
    "Karachi": "PK",
    "Kathmandu": "NP",
    "Kolkata": "IN",
    "Kuala Lumpur": "MY",
    "Kuwait City": "KW",
    "Kyiv": "UA",
    "Lahore": "PK",
    "Lanzhou": "CN",
    "Manila": "PH",
    "Mashhad": "IR",
    "Medan": "ID",
    "Mumbai": "IN",
    "Nagoya": "JP",
    "Nanchang": "CN",
    "Nanjing": "CN",
    "Nanning": "CN",
    "Naypyidaw": "MM",
    "Osaka": "JP",
    "Palembang": "ID",
    "Patna": "IN",
    "Phnom Penh": "KH",
    "Pune": "IN",
    "Qingdao": "CN",
    "Quito": "EC",
    "Recife": "BR",
    "Riverside": "US",
    "Riyadh": "SA",
    "Salvador": "SV",
    "San Antonio": "US",
    "San Diego": "US",
    "San Francisco": "US",
    "San Jose": "US",
    "Santa Cruz": "BO",
    "Sapporo": "JP",
    "Semarang": "ID",
    "Sendai": "JP",
    "Seoul": "KR",
    "Shanghai": "CN",
    "Shantou": "CN",
    "Shenyang": "CN",
    "Shenzhen": "CN",
    "Shijiazhuang": "CN",
    "Singapore": "SG",
    "Surat": "IN",
    "Suzhou": "CN",
    "Tabriz": "IR",
    "Taipei": "TW",
    "Taiyuan": "CN",
    "Tangshan": "CN",
    "Tashkent": "UZ",
    "Tehran": "IR",
    "Thessaloniki": "GR",
    "Tianjin": "CN",
    "Tijuana": "MX",
    "Tirana": "AL",
    "Tokyo": "JP",
    "Tunis": "TN",
    "Ulaanbaatar": "MN",
    "Urumqi": "CN",
    "Valencia": "ES",
    "Vancouver": "CA",
    "Vienna": "AT",
    "Warsaw": "PL",
    "Winnipeg": "CA",
    "Wuhan": "CN",
    "Xi'an": "CN",
    "Yangon": "MM",
    "Yekaterinburg": "RU",
    "Yerevan": "AM",
    "Zhengzhou": "CN",
    "Zibo": "CN",
    "Zurich": "CH",
    "Athens": "GR",
    "Barcelona": "ES",
    "Brussels": "BE",
    "Bucharest": "RO",
    "Budapest": "HU",
    "Copenhagen": "DK",
    "Dresden": "DE",
    "Edinburgh": "GB",
    "Frankfurt": "DE",
    "Geneva": "US",
    "Gothenburg": "SE",
    "Hamburg": "DE",
    "Helsinki": "FI",
    "Krakow": "PL",
    "Lisbon": "PT",
    "Ljubljana": "SI",
    "London": "GB",
    "Luxembourg": "BE",
    "Madrid": "ES",
    "Malaga": "ES",
    "Marseille": "FR",
    "Milan": "IT",
    "Monaco": "MC",
    "Moscow": "RU",
    "Munich": "DE",
    "Naples": "IT",
    "Nice": "FR",
    "Oslo": "NO",
    "Paris": "FR",
    "Prague": "CZ",
    "Reykjavik": "IS",
    "Riga": "LV",
    "Saint Petersburg": "RU",
    "Sarajevo": "BA",
    "Skopje": "MK",
    "Sofia": "BG",
    "Stuttgart": "DE",
    "Tallinn": "EE",
    "Tbilisi": "GE",
    "Thimphu": "BT",
    "Torshavn": "FO",
    "Valletta": "MT",
    "Vilnius": "LT",
    "Wellington": "NZ",
    "Zagreb": "HR",
    "Albuquerque": "US",
    "Anchorage": "US",
    "Arlington": "US",
    "Atlanta": "US",
    "Austin": "US",
    "Bakersfield": "US",
    "Baltimore": "US",
    "Boston": "US",
    "Chandler": "US",
    "Charlotte": "US",
    "Chesapeake": "US",
    "Chicago": "US",
    "Cincinnati": "US",
    "Cleveland": "US",
    "Colorado Springs": "US",
    "Columbus": "US",
    "Corpus Christi": "US",
    "Dallas": "US",
    "Denver": "US",
    "Detroit": "US",
    "Durham": "US",
    "El Paso": "US",
    "Fort Worth": "US",
    "Fresno": "US",
    "Garland": "US",
    "Glendale": "US",
    "Greensboro": "US",
    "Guadalajara": "MX",
    "Henderson": "US",
    "Hialeah": "US",
    "Honolulu": "US",
    "Houston": "US",
    "Indianapolis": "US",
    "Irvine": "US",
    "Irving": "US",
    "Jacksonville": "US",
    "Kansas City": "US",
    "Laredo": "US",
    "Las Vegas": "US",
    "Long Beach": "US",
    "Los Angeles": "US",
    "Louisville": "US",
    "Lubbock": "US",
    "Madison": "US",
    "Memphis": "US",
    "Mesa": "US",
    "Mexico City": "MX",
    "Miami": "US",
    "Milwaukee": "US",
    "Minneapolis": "US",
    "Nashville": "US",
    "New Orleans": "US",
    "New York": "US",
    "Norfolk": "US",
    "Oakland": "US",
    "Oklahoma City": "US",
    "Omaha": "US",
    "Orlando": "US",
    "Philadelphia": "US",
    "Phoenix": "US",
    "Pittsburgh": "US",
    "Plano": "US",
    "Portland": "US",
    "Raleigh": "US",
    "Reno": "US",
    "Sacramento": "US",
    "Scottsdale": "US",
    "Seattle": "US",
    "Shreveport": "US",
    "Spokane": "US",
    "St. Louis": "US",
    "St. Paul": "US",
    "St. Petersburg": "RU",
    "Stockton": "US",
    "Tampa": "US",
    "Toledo": "ES",
    "Toronto": "CA",
    "Tucson": "US",
    "Tulsa": "US",
    "Virginia Beach": "US",
    "Washington": "US",
    "Wichita": "US",
    "Winston-Salem": "US",
    "Asuncion": "PY",
    "Bogota": "CO",
    "Brasilia": "BR",
    "Buenos Aires": "AR",
    "Cali": "CO",
    "Caracas": "VE",
    "Curitiba": "BR",
    "Guayaquil": "EC",
    "Lima": "PE",
    "Managua": "NI",
    "Montevideo": "UY",
    "Panama City": "PA",
    "Port Louis": "MU",
    "Port Moresby": "PG",
    "Rio de Janeiro": "BR",
    "San Salvador": "SV",
    "Santiago": "CL",
    "Sao Paulo": "BR",
    "Adelaide": "AU",
    "Auckland": "NZ",
    "Brisbane": "AU",
    "Melbourne": "AU",
    "Newcastle": "AU",
    "Perth": "AU",
    "Pohnpei": "FM",
    "Sydney": "AU",
    "Abu Dhabi": "AE",
    "Al Hillah": "IQ",
    "Amara": "IQ",
    "Balad": "IQ",
    "Baqubah": "IQ",
    "Basra": "IQ",
    "Beirut": "LB",
    "Diwaniyah": "IQ",
    "Doha": "QA",
    "Dubai": "AE",
    "Erbil": "IQ",
    "Fallujah": "IQ",
    "Gaza": "PS",
    "Jerusalem": "IL",
    "Karbala": "IQ",
    "Kirkuk": "IQ",
    "Kufa": "IQ",
    "Kut": "IQ",
    "Manama": "BH",
    "Mosul": "IQ",
    "Muscat": "OM",
    "Najaf": "IQ",
    "Nasiriyah": "IQ",
    "Nicosia": "CY",
    "Ramallah": "PS",
    "Samarra": "IQ",
    "Sanaa": "YE",
    "Sulaymaniyah": "IQ",
    "Tikrit": "IQ",
    "Santo Domingo": "DO",
    "Havana": "CU", # Cuba
    "Guatemala City": "GT", # Guatemala
    "Port-au-Prince": "HT", # Haiti
    "San Juan": "AR",
    "Tegucigalpa": "HN", # Honduras
    "Kingston": "JM", # Jamaica
}


countries = {
    "AE": "United Arab Emirates",
    "AF": "Afghanistan",
    "AL": "Albania",
    "AM": "Armenia",
    "AO": "Angola",
    "AR": "Argentina",
    "AT": "Austria",
    "AU": "Australia",
    "AZ": "Azerbaijan",
    "BA": "Bosnia and Herzegovina",
    "BD": "Bangladesh",
    "BE": "Belgium",
    "BF": "Burkina Faso",
    "BG": "Bulgaria",
    "BH": "Bahrain",
    "BO": "Bolivia",
    "BR": "Brazil",
    "BT": "Bhutan",
    "CA": "Canada",
    "CD": "Democratic Republic of the Congo",
    "CH": "Switzerland",
    "CI": "Côte d'Ivoire",
    "CL": "Chile",
    "CM": "Cameroon",
    "CN": "China",
    "CO": "Colombia",
    "CR": "Costa Rica",
    "CU": "Cuba",
    "CY": "Cyprus",
    "CZ": "Czech Republic",
    "DE": "Germany",
    "DK": "Denmark",
    "DO": "Dominican Republic",
    "DZ": "Algeria",
    "EC": "Ecuador",
    "EE": "Estonia",
    "EG": "Egypt",
    "ES": "Spain",
    "ET": "Ethiopia",
    "FI": "Finland",
    "FM": "Micronesia",
    "FO": "Faroe Islands",
    "FR": "France",
    "GB": "United Kingdom",
    "GE": "Georgia",
    "GH": "Ghana",
    "GT": "Guatemala",
    "GR": "Greece",
    "HT": "Haiti",
    "HK": "Hong Kong",
    "HN": "Honduras",
    "HR": "Croatia",
    "HU": "Hungary",
    "ID": "Indonesia",
    "IL": "Israel",
    "IN": "India",
    "IQ": "Iraq",
    "IR": "Iran",
    "IS": "Iceland",
    "IT": "Italy",
    "JM": "Jamaica",
    "JO": "Jordan",
    "JP": "Japan",
    "KE": "Kenya",
    "KG": "Kyrgyzstan",
    "KH": "Cambodia",
    "KR": "South Korea",
    "KW": "Kuwait",
    "KZ": "Kazakhstan",
    "LB": "Lebanon",
    "LK": "Sri Lanka",
    "LR": "Liberia",
    "LT": "Lithuania",
    "LV": "Latvia",
    "MA": "Morocco",
    "MC": "Monaco",
    "MG": "Madagascar",
    "MK": "North Macedonia",
    "ML": "Mali",
    "MM": "Myanmar",
    "MN": "Mongolia",
    "MT": "Malta",
    "MU": "Mauritius",
    "MX": "Mexico",
    "MY": "Malaysia",
    "MZ": "Mozambique",
    "NE": "Niger",
    "NG": "Nigeria",
    "NI": "Nicaragua",
    "NO": "Norway",
    "NP": "Nepal",
    "NZ": "New Zealand",
    "OM": "Oman",
    "PA": "Panama",
    "PE": "Peru",
    "PG": "Papua New Guinea",
    "PH": "Philippines",
    "PK": "Pakistan",
    "PL": "Poland",
    "PS": "Palestine",
    "PT": "Portugal",
    "PY": "Paraguay",
    "QA": "Qatar",
    "RO": "Romania",
    "RU": "Russia",
    "RW": "Rwanda",
    "SA": "Saudi Arabia",
    "SD": "Sudan",
    "SE": "Sweden",
    "SG": "Singapore",
    "SI": "Slovenia",
    "SN": "Senegal",
    "SV": "El Salvador",
    "SY": "Syria",
    "TH": "Thailand",
    "TN": "Tunisia",
    "TR": "Turkey",
    "TW": "Taiwan",
    "TZ": "Tanzania",
    "UA": "Ukraine",
    "US": "United States",
    "UY": "Uruguay",
    "UZ": "Uzbekistan",
    "VE": "Venezuela",
    "VN": "Vietnam",
    "YE": "Yemen",
    "ZA": "South Africa",
    "ZM": "Zambia",
}


us_cities = {
    "Albuquerque": "New Mexico",
    "Anchorage": "Alaska",
    "Arlington": "Texas",
    "Atlanta": "Georgia",
    "Austin": "Texas",
    "Bakersfield": "California",
    "Baltimore": "Maryland",
    "Boston": "Massachusetts",
    "Chandler": "Arizona",
    "Charlotte": "North Carolina",
    "Chesapeake": "Virginia",
    "Chicago": "Illinois",
    "Cincinnati": "Ohio",
    "Cleveland": "Ohio",
    "Colorado Springs": "Colorado",
    "Columbus": "Ohio",
    "Corpus Christi": "Texas",
    "Dallas": "Texas",
    "Denver": "Colorado",
    "Detroit": "Michigan",
    "Durham": "North Carolina",
    "El Paso": "Texas",
    "Fairbanks": "Alaska",
    "Fort Worth": "Texas",
    "Fresno": "California",
    "Garland": "Texas",
    "Geneva": "Illinois",
    "Glendale": "Arizona",
    "Greensboro": "North Carolina",
    "Henderson": "Nevada",
    "Hialeah": "Florida",
    "Honolulu": "Hawaii",
    "Houston": "Texas",
    "Indianapolis": "Indiana",
    "Irvine": "California",
    "Irving": "Texas",
    "Jacksonville": "Florida",
    "Kansas City": "Missouri",
    "Laredo": "Texas",
    "Las Vegas": "Nevada",
    "Long Beach": "California",
    "Los Angeles": "California",
    "Louisville": "Kentucky",
    "Lubbock": "Texas",
    "Madison": "Wisconsin",
    "Memphis": "Tennessee",
    "Mesa": "Arizona",
    "Miami": "Florida",
    "Milwaukee": "Wisconsin",
    "Minneapolis": "Minnesota",
    "Nashville": "Tennessee",
    "New Orleans": "Louisiana",
    "New York City": "New York",
    "Norfolk": "Virginia",
    "Oakland": "California",
    "Oklahoma City": "Oklahoma",
    "Omaha": "Nebraska",
    "Orlando": "Florida",
    "Philadelphia": "Pennsylvania",
    "Phoenix": "Arizona",
    "Pittsburgh": "Pennsylvania",
    "Plano": "Texas",
    "Portland": "Oregon",
    "Raleigh": "North Carolina",
    "Reno": "Nevada",
    "Riverside": "California",
    "Sacramento": "California",
    "San Antonio": "Texas",
    "San Diego": "California",
    "San Francisco": "California",
    "San Jose": "California",
    "Scottsdale": "Arizona",
    "Seattle": "Washington",
    "Shreveport": "Louisiana",
    "Spokane": "Washington",
    "St. Louis": "Missouri",
    "St. Paul": "Minnesota",
    "Stockton": "California",
    "Tampa": "Florida",
    "Tucson": "Arizona",
    "Tulsa": "Oklahoma",
    "Virginia Beach": "Virginia",
    "Washington": "District of Columbia",
    "Wichita": "Kansas",
    "Winston-Salem": "North Carolina",
}
