weather_descriptions = {
    "broken clouds": "broken_clouds.png",
    "clear sky": "clear_sky.png",
    "drizzle": "drizzle.png",
    "few clouds": "broken_clouds.png",
    "haze": "haze.png",
    "light intensity drizzle": "drizzle.png",
    "light intensity shower rain": "light_showers_2.png",
    "light rain": "light_rain.png",
    "light snow": "snow.png",
    "mist": "mist.png",
    "moderate rain": "moderate_rain.png",
    "overcast clouds": "broken_clouds.png",
    "scattered clouds": "broken_clouds.png",
    "showers": "heavy_showers.png",
    "smoke": "smoke.png",
    "snow": "snow.png",
    "thunderstorm": "thunderstorm.png",
}
